name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  swipeable_card_stack: ^0.0.5

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/baeco/
    - lib/assets/images/LorongTemu/
    - lib/assets/images/Maraloka/
    - lib/assets/images/secretGarden/
    - lib/assets/images/tomoro/
    - lib/assets/images/kopitarium/
    - lib/assets/images/Menata/
    - lib/assets/images/Ninety/
    - lib/assets/images/Selakopi/
    - lib/assets/images/sondasaji/
    - lib/assets/images/curugCibeureum/
    - lib/assets/images/curugCikondang/
    - lib/assets/images/pantaiKarangPotong/
    - lib/assets/images/telagaBiru/
    - lib/assets/images/theNice/
    - lib/assets/images/kebunRayaCibodas/
    - lib/assets/images/pantaiJayanti/
    - lib/assets/lottie/
