name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  swipeable_card_stack: ^0.0.5

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/lottie/
